#!/bin/bash

pkgname=int
pkgarch=all
pkgdefaultversion=1.0
execpath=/usr/bin
execnewname=int
execoldname=int.py
pkgversion=$(cat int.py | grep "^Version" | grep -Po '((?:[0-9]\.)+[0-9])|(?<=\")\d(?=\")')

if [ -d "$pkgname"_"$pkgversion"_"$pkgarch" ]; then
	echo "removing old build environment"
	rm -rf "$pkgname"_"$pkgversion"_"$pkgarch"
fi

mkdir -p "$pkgname"_"$pkgversion"_"$pkgarch"/usr/bin
cp -r "$pkgname"_"$pkgdefaultversion"_"$pkgarch"/* "$pkgname"_"$pkgversion"_"$pkgarch"
cp "$execoldname" "$pkgname"_"$pkgversion"_"$pkgarch""$execpath"/"$execnewname"

chmod +x "$pkgname"_"$pkgversion"_"$pkgarch""$execpath"/"$execnewname"
chmod -w "$pkgname"_"$pkgversion"_"$pkgarch""$execpath"/"$execnewname"

sed -i -e s/"$pkgdefaultversion"/"$pkgversion"/g "$pkgname"_"$pkgversion"_"$pkgarch"/DEBIAN/control

dpkg-deb --build "$pkgname"_"$pkgversion"_"$pkgarch"

unset pkgname pkgarch pkgdefaultversion pkgversion execpath execnewname execoldname
