#!/bin/bash

pkgversion=$(cat int.py | grep "^Version" | grep -Po '((?:[0-9]\.)+[0-9])|(?<=\")\d(?=\")')

if [ -f "int_${pkgversion}_all.deb" ]; then
	echo "removing old build"
	rm -rf "int_${pkgversion}_all"
fi

mkdir -p "int_${pkgversion}_all/DEBIAN"
mkdir -p "int_${pkgversion}_all/usr/bin"
cp control "int_${pkgversion}_all/DEBIAN"
cp int.py "int_${pkgversion}_all/usr/bin"
pushd "int_${pkgversion}_all/usr/bin" > /dev/null
chmod -w int.py
chmod +x int.py
mv int.py int
popd > /dev/null

sed -i -e "s/1.0/${pkgversion}/g" "int_${pkgversion}_all/DEBIAN/control"

dpkg-deb --build "int_${pkgversion}_all"

rm -rf "int_${pkgversion}_all"
